language: node_js
node_js:
  - 'iojs-v2.4.0'
services:
  - redis-server
env:
  CODECLIMATE_REPO_TOKEN=0af717d08c45d155b504c197597bc7716bfc0d50f82548fafbcc2b43c1e6c97d
before_script:
  - export PATH="$PATH:$(npm bin)"
script:
  - npm test
after_script:
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < lcov.info
